"""
Seeds AssessmentQuestion with 20 questions per domain (140 total).

Run once: python seed_questions.py

Safe to re-run: it clears existing rows for each domain before inserting,
so you won't end up with duplicates if you run it more than once.
"""
from app import app, db, AssessmentQuestion

questions = [
    # ───────────────────────── Engineering & Technology ─────────────────────────
    dict(domain="engineering_tech", question="What does HTML stand for?",
         option_a="Hyper Text Markup Language", option_b="High Transfer Machine Language",
         option_c="Home Tool Markup Language", option_d="Hyper Tool Multi Language", correct_answer=0),
    dict(domain="engineering_tech", question="Which language is primarily used for styling web pages?",
         option_a="Python", option_b="CSS", option_c="C++", option_d="Java", correct_answer=1),
    dict(domain="engineering_tech", question="What does API stand for?",
         option_a="Application Programming Interface", option_b="Advanced Program Integration",
         option_c="Applied Process Interaction", option_d="Automated Program Instruction", correct_answer=0),
    dict(domain="engineering_tech", question="Which data structure follows First-In-First-Out (FIFO)?",
         option_a="Stack", option_b="Tree", option_c="Queue", option_d="Graph", correct_answer=2),
    dict(domain="engineering_tech", question="What does SQL stand for?",
         option_a="Structured Query Language", option_b="Simple Question Language",
         option_c="Sequential Query Logic", option_d="System Query Language", correct_answer=0),
    dict(domain="engineering_tech", question="Which of these is a distributed version control system?",
         option_a="Docker", option_b="Git", option_c="Jenkins", option_d="Kubernetes", correct_answer=1),
    dict(domain="engineering_tech", question="What is the average time complexity of binary search on a sorted array?",
         option_a="O(n)", option_b="O(n^2)", option_c="O(log n)", option_d="O(1)", correct_answer=2),
    dict(domain="engineering_tech", question="Which language runs natively inside a web browser?",
         option_a="Java", option_b="C#", option_c="JavaScript", option_d="Go", correct_answer=2),
    dict(domain="engineering_tech", question="What does IDE stand for?",
         option_a="Integrated Development Environment", option_b="Internal Design Engine",
         option_c="Interactive Debug Editor", option_d="Independent Development Executable", correct_answer=0),
    dict(domain="engineering_tech", question="Which HTTP method is typically used to retrieve data without modifying it?",
         option_a="POST", option_b="DELETE", option_c="GET", option_d="PUT", correct_answer=2),
    dict(domain="engineering_tech", question="What does the acronym 'REST' commonly refer to in web APIs?",
         option_a="Representational State Transfer", option_b="Remote Service Transmission",
         option_c="Reliable State Transport", option_d="Recursive State Tracker", correct_answer=0),
    dict(domain="engineering_tech", question="Which of these is a NoSQL database?",
         option_a="PostgreSQL", option_b="MySQL", option_c="MongoDB", option_d="Oracle DB", correct_answer=2),
    dict(domain="engineering_tech", question="In object-oriented programming, what is 'inheritance'?",
         option_a="Deleting unused variables automatically", option_b="A class acquiring properties/methods of another class",
         option_c="Compiling code faster", option_d="Encrypting stored data", correct_answer=1),
    dict(domain="engineering_tech", question="What is the purpose of a firewall in networking?",
         option_a="To speed up internet connections", option_b="To monitor/control incoming and outgoing network traffic",
         option_c="To compress large files", option_d="To generate IP addresses", correct_answer=1),
    dict(domain="engineering_tech", question="Which of these best describes 'Big O notation'?",
         option_a="A way to measure code readability", option_b="A way to describe an algorithm's growth in time/space",
         option_c="A programming language", option_d="A database indexing method", correct_answer=1),
    dict(domain="engineering_tech", question="What does CPU stand for?",
         option_a="Central Processing Unit", option_b="Computer Personal Unit",
         option_c="Central Program Utility", option_d="Core Processing Utility", correct_answer=0),
    dict(domain="engineering_tech", question="Which of the following is used to containerize applications?",
         option_a="Docker", option_b="Photoshop", option_c="Excel", option_d="Figma", correct_answer=0),
    dict(domain="engineering_tech", question="What is the main purpose of a compiler?",
         option_a="To design user interfaces", option_b="To translate source code into machine code",
         option_c="To manage databases", option_d="To browse the internet", correct_answer=1),
    dict(domain="engineering_tech", question="Which protocol is used to securely transfer data over the web?",
         option_a="FTP", option_b="HTTP", option_c="HTTPS", option_d="SMTP", correct_answer=2),
    dict(domain="engineering_tech", question="What does 'debugging' mean in software development?",
         option_a="Writing new features", option_b="Finding and fixing errors in code",
         option_c="Designing the UI", option_d="Deploying to production", correct_answer=1),

    # ───────────────────────── Medical & Healthcare ─────────────────────────
    dict(domain="medical_healthcare", question="What is the normal resting heart rate range for a healthy adult (beats per minute)?",
         option_a="20-40", option_b="60-100", option_c="120-160", option_d="180-220", correct_answer=1),
    dict(domain="medical_healthcare", question="Which organ is primarily responsible for filtering blood and producing urine?",
         option_a="Liver", option_b="Kidney", option_c="Pancreas", option_d="Spleen", correct_answer=1),
    dict(domain="medical_healthcare", question="What does 'BP' commonly stand for in a clinical setting?",
         option_a="Body Pulse", option_b="Blood Pressure", option_c="Breathing Pattern", option_d="Bone Position", correct_answer=1),
    dict(domain="medical_healthcare", question="Which blood type is known as the 'universal donor'?",
         option_a="AB+", option_b="A-", option_c="O-", option_d="B+", correct_answer=2),
    dict(domain="medical_healthcare", question="What is the medical term for high blood sugar?",
         option_a="Hypoglycemia", option_b="Hyperglycemia", option_c="Hypertension", option_d="Hypotension", correct_answer=1),
    dict(domain="medical_healthcare", question="Which gland regulates metabolism by producing hormones like T3 and T4?",
         option_a="Pituitary gland", option_b="Adrenal gland", option_c="Thyroid gland", option_d="Pineal gland", correct_answer=2),
    dict(domain="medical_healthcare", question="What does 'CPR' stand for?",
         option_a="Cardiopulmonary Resuscitation", option_b="Clinical Patient Report",
         option_c="Chronic Pain Relief", option_d="Cardiac Pressure Reading", correct_answer=0),
    dict(domain="medical_healthcare", question="Which of these is NOT one of the four main blood components?",
         option_a="Plasma", option_b="Red blood cells", option_c="White blood cells", option_d="Synovial fluid", correct_answer=3),
    dict(domain="medical_healthcare", question="What is the normal human body temperature (approximate, in Celsius)?",
         option_a="32°C", option_b="37°C", option_c="42°C", option_d="45°C", correct_answer=1),
    dict(domain="medical_healthcare", question="Which vitamin is primarily produced when skin is exposed to sunlight?",
         option_a="Vitamin A", option_b="Vitamin C", option_c="Vitamin D", option_d="Vitamin K", correct_answer=2),
    dict(domain="medical_healthcare", question="What is the main function of red blood cells?",
         option_a="Fighting infection", option_b="Clotting blood", option_c="Carrying oxygen", option_d="Producing antibodies", correct_answer=2),
    dict(domain="medical_healthcare", question="Which term describes inflammation of the liver?",
         option_a="Nephritis", option_b="Hepatitis", option_c="Gastritis", option_d="Arthritis", correct_answer=1),
    dict(domain="medical_healthcare", question="What does 'ICU' stand for in a hospital setting?",
         option_a="Intensive Care Unit", option_b="Internal Clinical Unit",
         option_c="Immediate Care Utility", option_d="Infection Control Unit", correct_answer=0),
    dict(domain="medical_healthcare", question="Which of these is a common symptom of dehydration?",
         option_a="Excess sweating only", option_b="Dark urine and dry mouth",
         option_c="Lowered heart rate", option_d="Increased appetite", correct_answer=1),
    dict(domain="medical_healthcare", question="What is the primary purpose of a vaccine?",
         option_a="To cure an existing infection immediately", option_b="To train the immune system to recognize a pathogen",
         option_c="To replace lost blood cells", option_d="To reduce body temperature", correct_answer=1),
    dict(domain="medical_healthcare", question="Which of these professionals typically administers anesthesia during surgery?",
         option_a="Radiologist", option_b="Anesthesiologist", option_c="Dermatologist", option_d="Pathologist", correct_answer=1),
    dict(domain="medical_healthcare", question="What does 'BMI' stand for?",
         option_a="Body Mass Index", option_b="Blood Metabolic Indicator",
         option_c="Basic Medical Information", option_d="Body Motion Index", correct_answer=0),
    dict(domain="medical_healthcare", question="Which organ produces insulin?",
         option_a="Liver", option_b="Pancreas", option_c="Kidney", option_d="Gallbladder", correct_answer=1),
    dict(domain="medical_healthcare", question="What is the term for the study of diseases?",
         option_a="Pathology", option_b="Physiology", option_c="Pharmacology", option_d="Anatomy", correct_answer=0),
    dict(domain="medical_healthcare", question="Which of these best describes 'triage' in emergency medicine?",
         option_a="A type of surgical stitch", option_b="Sorting patients by urgency of treatment needed",
         option_c="A diagnostic imaging technique", option_d="A category of medication", correct_answer=1),

    # ───────────────────────── Commerce & Finance ─────────────────────────
    dict(domain="commerce_finance", question="What does 'GDP' stand for?",
         option_a="Gross Domestic Product", option_b="General Development Plan",
         option_c="Global Distribution Process", option_d="Gross Deposit Percentage", correct_answer=0),
    dict(domain="commerce_finance", question="Which financial statement shows a company's revenues and expenses over a period?",
         option_a="Balance Sheet", option_b="Income Statement", option_c="Cash Flow Statement", option_d="Trial Balance", correct_answer=1),
    dict(domain="commerce_finance", question="What is 'inflation'?",
         option_a="A decrease in the money supply", option_b="A general rise in prices over time",
         option_c="A fixed exchange rate policy", option_d="A type of tax", correct_answer=1),
    dict(domain="commerce_finance", question="What does 'ROI' stand for?",
         option_a="Return On Investment", option_b="Rate Of Interest",
         option_c="Revenue Over Income", option_d="Ratio Of Inputs", correct_answer=0),
    dict(domain="commerce_finance", question="Which of these is considered a current asset?",
         option_a="Land", option_b="Cash", option_c="Buildings", option_d="Machinery", correct_answer=1),
    dict(domain="commerce_finance", question="What is the primary function of a central bank?",
         option_a="Selling retail products", option_b="Regulating monetary policy and currency supply",
         option_c="Manufacturing goods", option_d="Managing employee payroll for companies", correct_answer=1),
    dict(domain="commerce_finance", question="What does 'equity' represent in a company's balance sheet?",
         option_a="Total liabilities", option_b="Owners' residual claim on assets after liabilities",
         option_c="Total revenue", option_d="Total expenses", correct_answer=1),
    dict(domain="commerce_finance", question="Which term describes the practice of spreading investments to reduce risk?",
         option_a="Diversification", option_b="Leverage", option_c="Arbitrage", option_d="Liquidation", correct_answer=0),
    dict(domain="commerce_finance", question="What does 'GST' commonly stand for in the Indian tax system?",
         option_a="General Sales Tariff", option_b="Goods and Services Tax",
         option_c="Government Service Tax", option_d="Gross Standard Tax", correct_answer=1),
    dict(domain="commerce_finance", question="What is a 'bull market'?",
         option_a="A market with falling prices", option_b="A market with rising prices and investor optimism",
         option_c="A market with no trading activity", option_d="A market only for commodities", correct_answer=1),
    dict(domain="commerce_finance", question="What does 'liability' mean in accounting?",
         option_a="Money a business owns", option_b="Money a business owes to others",
         option_c="Profit earned by a business", option_d="Total number of employees", correct_answer=1),
    dict(domain="commerce_finance", question="Which of these best defines 'compound interest'?",
         option_a="Interest calculated only on the principal amount", option_b="Interest calculated on principal plus accumulated interest",
         option_c="A one-time fee on a loan", option_d="Interest that never changes over time", correct_answer=1),
    dict(domain="commerce_finance", question="What is the main purpose of a budget?",
         option_a="To track and plan income and expenses", option_b="To increase taxes automatically",
         option_c="To hire new employees", option_d="To register a business legally", correct_answer=0),
    dict(domain="commerce_finance", question="What does 'IPO' stand for?",
         option_a="Initial Public Offering", option_b="Internal Profit Order",
         option_c="Investment Policy Outline", option_d="International Payment Option", correct_answer=0),
    dict(domain="commerce_finance", question="Which of these is a direct tax?",
         option_a="Income Tax", option_b="Sales Tax", option_c="Excise Duty", option_d="Customs Duty", correct_answer=0),
    dict(domain="commerce_finance", question="What does 'liquidity' refer to in finance?",
         option_a="How quickly an asset can be converted to cash", option_b="The total debt of a company",
         option_c="The profit margin of a business", option_d="The number of shareholders", correct_answer=0),
    dict(domain="commerce_finance", question="What is a 'stock dividend'?",
         option_a="A penalty for late tax filing", option_b="A payment made by a company to shareholders from profits",
         option_c="A loan given by a bank", option_d="A government subsidy", correct_answer=1),
    dict(domain="commerce_finance", question="What does 'break-even point' mean in business?",
         option_a="The point where total revenue equals total costs", option_b="The maximum profit a business can earn",
         option_c="The point of business closure", option_d="The starting capital of a business", correct_answer=0),
    dict(domain="commerce_finance", question="Which of these best describes 'supply and demand'?",
         option_a="A government regulation on prices", option_b="An economic model explaining price determination in a market",
         option_c="A type of business license", option_d="A method of calculating taxes", correct_answer=1),
    dict(domain="commerce_finance", question="What is 'net profit'?",
         option_a="Total revenue before any deductions", option_b="Revenue remaining after all expenses, taxes, and costs are deducted",
         option_c="The total value of assets", option_d="The amount of tax owed", correct_answer=1),

    # ───────────────────────── Law ─────────────────────────
    dict(domain="law", question="What is the term for a written, formal agreement between two or more parties?",
         option_a="Affidavit", option_b="Contract", option_c="Subpoena", option_d="Deposition", correct_answer=1),
    dict(domain="law", question="What does 'plaintiff' mean in a legal case?",
         option_a="The person accused of a crime", option_b="The person who initiates a lawsuit",
         option_c="The judge presiding over the case", option_d="A witness called to testify", correct_answer=1),
    dict(domain="law", question="What is 'jurisdiction'?",
         option_a="A type of legal document", option_b="The official authority of a court to hear and decide a case",
         option_c="A penalty for breaking a contract", option_d="A category of criminal offense", correct_answer=1),
    dict(domain="law", question="What does 'bail' refer to in criminal law?",
         option_a="A permanent release from all charges", option_b="Temporary release of an accused person pending trial, often with conditions",
         option_c="A type of criminal sentence", option_d="A lawyer's fee", correct_answer=1),
    dict(domain="law", question="What is the purpose of 'evidence' in a legal trial?",
         option_a="To decorate the courtroom", option_b="To support or refute claims made by parties in a case",
         option_c="To determine court fees", option_d="To schedule hearing dates", correct_answer=1),
    dict(domain="law", question="What does 'defendant' mean?",
         option_a="The party being accused or sued in a legal case", option_b="The judge in a criminal trial",
         option_c="The lawyer representing the plaintiff", option_d="A member of the jury", correct_answer=0),
    dict(domain="law", question="What is 'intellectual property' primarily concerned with?",
         option_a="Physical land ownership", option_b="Creations of the mind, such as inventions and trademarks",
         option_c="Government tax policy", option_d="Employment contracts only", correct_answer=1),
    dict(domain="law", question="What does 'litigation' refer to?",
         option_a="The process of resolving disputes through court proceedings", option_b="Signing a business contract",
         option_c="Drafting a will", option_d="Paying legal fees in advance", correct_answer=0),
    dict(domain="law", question="What is a 'tort' in law?",
         option_a="A criminal offense only", option_b="A civil wrong that causes harm or loss to another person",
         option_c="A type of business license", option_d="A government regulation on trade", correct_answer=1),
    dict(domain="law", question="What does 'pro bono' mean in legal practice?",
         option_a="Charging premium fees", option_b="Providing legal services voluntarily and free of charge",
         option_c="A type of court appeal", option_d="Legal representation for corporations only", correct_answer=1),
    dict(domain="law", question="What is the role of a 'notary public'?",
         option_a="To prosecute criminal cases", option_b="To witness and certify the signing of documents",
         option_c="To represent defendants in court", option_d="To draft new legislation", correct_answer=1),
    dict(domain="law", question="What does 'appeal' mean in a legal context?",
         option_a="Requesting a higher court to review a lower court's decision", option_b="Filing the initial complaint in a case",
         option_c="Settling a dispute out of court", option_d="Serving a summons to a witness", correct_answer=0),
    dict(domain="law", question="What is 'due process'?",
         option_a="A guarantee of fair legal proceedings before depriving someone of life, liberty, or property", option_b="A type of contract clause",
         option_c="A tax filing deadline", option_d="A police arrest procedure only", correct_answer=0),
    dict(domain="law", question="What does 'testimony' refer to?",
         option_a="A written contract", option_b="A statement given by a witness under oath",
         option_c="A court's final judgment", option_d="A legal fee structure", correct_answer=1),
    dict(domain="law", question="What is the purpose of a 'will' in law?",
         option_a="To resolve business disputes", option_b="To specify how a person's assets are distributed after death",
         option_c="To register a marriage", option_d="To file for bankruptcy", correct_answer=1),
    dict(domain="law", question="What does 'acquittal' mean?",
         option_a="A formal finding of guilt", option_b="A formal declaration that an accused person is not guilty",
         option_c="A request for a retrial", option_d="A type of civil settlement", correct_answer=1),
    dict(domain="law", question="What is 'arbitration'?",
         option_a="A method of resolving disputes outside of court using a neutral third party", option_b="A criminal sentencing process",
         option_c="A type of legal fee", option_d="A government audit", correct_answer=0),
    dict(domain="law", question="What does 'statute' mean in law?",
         option_a="A written law passed by a legislative body", option_b="A verbal agreement",
         option_c="A court's physical location", option_d="A lawyer's professional title", correct_answer=0),
    dict(domain="law", question="What is 'custody' in family law typically concerned with?",
         option_a="Ownership of a business", option_b="The care and guardianship of a child",
         option_c="The division of company assets", option_d="Tax filing status", correct_answer=1),
    dict(domain="law", question="What does 'liable' mean in a legal context?",
         option_a="Being legally responsible for something", option_b="Being exempt from all legal obligations",
         option_c="Winning a court case automatically", option_d="Being a licensed attorney", correct_answer=0),

    # ───────────────────────── Design & Creative Arts ─────────────────────────
    dict(domain="design_creative", question="What are the three primary colors in traditional color theory?",
         option_a="Red, Green, Blue", option_b="Red, Yellow, Blue", option_c="Cyan, Magenta, Yellow", option_d="Black, White, Grey", correct_answer=1),
    dict(domain="design_creative", question="What does 'typography' refer to?",
         option_a="The study and use of fonts and text arrangement", option_b="A type of color palette",
         option_c="A photo editing technique", option_d="A 3D modeling method", correct_answer=0),
    dict(domain="design_creative", question="What is 'negative space' in design?",
         option_a="The empty space around and between design elements", option_b="A color scheme using only black tones",
         option_c="A type of font weight", option_d="An error in a design file", correct_answer=0),
    dict(domain="design_creative", question="Which file format is best suited for logos that need to scale without losing quality?",
         option_a="JPEG", option_b="SVG (vector format)", option_c="BMP", option_d="MP4", correct_answer=1),
    dict(domain="design_creative", question="What does 'UI' stand for in design?",
         option_a="User Interface", option_b="Universal Icon", option_c="Unified Illustration", option_d="User Instruction", correct_answer=0),
    dict(domain="design_creative", question="What does 'UX' stand for?",
         option_a="User Experience", option_b="Unified Export", option_c="Universal Exchange", option_d="User Extension", correct_answer=0),
    dict(domain="design_creative", question="Which color model is used for digital screens (RGB stands for)?",
         option_a="Red, Grey, Black", option_b="Red, Green, Blue", option_c="Rich, Gold, Bronze", option_d="Round, Grid, Border", correct_answer=1),
    dict(domain="design_creative", question="What is a 'mood board' typically used for?",
         option_a="Tracking a project's budget", option_b="Visually gathering inspiration and design direction",
         option_c="Writing project documentation", option_d="Scheduling client meetings", correct_answer=1),
    dict(domain="design_creative", question="What does 'CMYK' stand for in print design?",
         option_a="Cyan, Magenta, Yellow, Key (black)", option_b="Color, Mode, Yield, Key",
         option_c="Contrast, Margin, Yaw, Kerning", option_d="Cyan, Maroon, Yellow, Khaki", correct_answer=0),
    dict(domain="design_creative", question="What is 'kerning' in typography?",
         option_a="The size of a font", option_b="The adjustment of space between individual letter pairs",
         option_c="The color of the text", option_d="The font family name", correct_answer=1),
    dict(domain="design_creative", question="What does 'wireframe' mean in UI/UX design?",
         option_a="A final polished visual design", option_b="A basic structural layout blueprint of a screen or page",
         option_c="A type of animation", option_d="A color palette generator", correct_answer=1),
    dict(domain="design_creative", question="Which principle refers to balancing visual weight across a composition?",
         option_a="Contrast", option_b="Balance", option_c="Repetition", option_d="Alignment", correct_answer=1),
    dict(domain="design_creative", question="What is a 'style guide' in design work?",
         option_a="A document defining consistent visual standards (colors, fonts, spacing, etc.)", option_b="A tutorial on using design software",
         option_c="A client's budget breakdown", option_d="A portfolio of past projects", correct_answer=0),
    dict(domain="design_creative", question="What does 'DPI' stand for in image resolution?",
         option_a="Dots Per Inch", option_b="Digital Pixel Index", option_c="Design Print Interval", option_d="Data Processing Instruction", correct_answer=0),
    dict(domain="design_creative", question="What is 'prototyping' in the design process?",
         option_a="Writing the final code for a product", option_b="Creating an early interactive or visual sample to test ideas",
         option_c="Marketing a finished product", option_d="Archiving old design files", correct_answer=1),
    dict(domain="design_creative", question="Which of these best describes 'visual hierarchy'?",
         option_a="Arranging elements to show their order of importance", option_b="Using only one color in a design",
         option_c="A rule requiring symmetrical layouts", option_d="The file size of a design document", correct_answer=0),
    dict(domain="design_creative", question="What does 'brand identity' encompass?",
         option_a="Only a company's logo", option_b="The visual and conceptual elements that represent a brand (logo, colors, tone, etc.)",
         option_c="A company's tax filings", option_d="A product's manufacturing process", correct_answer=1),
    dict(domain="design_creative", question="What is 'responsive design'?",
         option_a="A design that adapts its layout to different screen sizes", option_b="A design that changes color randomly",
         option_c="A design tool for 3D modeling", option_d="A printing technique for posters", correct_answer=0),
    dict(domain="design_creative", question="What does 'contrast' refer to in visual design?",
         option_a="The difference between design elements (e.g. light vs dark) to create emphasis", option_b="The total number of colors used",
         option_c="The file format of an image", option_d="The speed of an animation", correct_answer=0),
    dict(domain="design_creative", question="What is a 'grid system' used for in layout design?",
         option_a="Storing design files", option_b="Aligning and organizing content consistently across a page",
         option_c="Compressing images", option_d="Choosing brand colors", correct_answer=1),

    # ───────────────────────── Government & Public Services ─────────────────────────
    dict(domain="government_public", question="What is the primary role of a legislature in government?",
         option_a="Enforcing laws", option_b="Making and passing laws", option_c="Interpreting laws in court", option_d="Collecting taxes directly", correct_answer=1),
    dict(domain="government_public", question="What does 'public policy' refer to?",
         option_a="A private company's internal rules", option_b="A course of action adopted by a government to address public issues",
         option_c="A type of tax exemption", option_d="A political party's membership list", correct_answer=1),
    dict(domain="government_public", question="What is the function of the judiciary in a government system?",
         option_a="Interpreting and applying laws", option_b="Drafting the national budget",
         option_c="Managing public elections", option_d="Running state-owned businesses", correct_answer=0),
    dict(domain="government_public", question="What does 'civil service' refer to?",
         option_a="Volunteer work in local communities", option_b="Employment in government administrative roles",
         option_c="Military service", option_d="A private legal firm", correct_answer=1),
    dict(domain="government_public", question="What is a 'census'?",
         option_a="A type of election", option_b="An official count/survey of a population",
         option_c="A government budget report", option_d="A court proceeding", correct_answer=1),
    dict(domain="government_public", question="What does 'decentralization' mean in public administration?",
         option_a="Concentrating all power in a central authority", option_b="Distributing authority and decision-making to local/regional levels",
         option_c="Abolishing local governments entirely", option_d="Privatizing all public services", correct_answer=1),
    dict(domain="government_public", question="What is the main purpose of public welfare programs?",
         option_a="To generate government revenue", option_b="To provide support and services to citizens in need",
         option_c="To regulate private businesses", option_d="To manage foreign trade agreements", correct_answer=1),
    dict(domain="government_public", question="What does 'bureaucracy' typically refer to?",
         option_a="A system of government administration through structured departments and procedures", option_b="A type of election system",
         option_c="A political ideology", option_d="A form of taxation", correct_answer=0),
    dict(domain="government_public", question="What is 'e-governance'?",
         option_a="The use of digital technology to deliver government services", option_b="A type of electoral campaign",
         option_c="A private sector consulting practice", option_d="A method of tax collection only", correct_answer=0),
    dict(domain="government_public", question="What is the role of an ombudsman in public service?",
         option_a="To draft new legislation", option_b="To investigate public complaints against government agencies",
         option_c="To manage the national budget", option_d="To oversee elections", correct_answer=1),
    dict(domain="government_public", question="What does 'public administration' primarily study?",
         option_a="Private business management", option_b="The implementation of government policy and management of public programs",
         option_c="International trade law", option_d="Corporate finance", correct_answer=1),
    dict(domain="government_public", question="What is a 'referendum'?",
         option_a="A direct vote by citizens on a specific policy question", option_b="A court ruling on a constitutional matter",
         option_c="A government budget document", option_d="A diplomatic treaty", correct_answer=0),
    dict(domain="government_public", question="What does 'transparency' mean in governance?",
         option_a="Keeping government operations confidential", option_b="Openness and accessibility of government actions and information to the public",
         option_c="A type of tax policy", option_d="A voting method", correct_answer=1),
    dict(domain="government_public", question="What is the main function of a municipal government?",
         option_a="Managing national defense", option_b="Providing local services like sanitation, roads, and water supply",
         option_c="Setting national foreign policy", option_d="Printing currency", correct_answer=1),
    dict(domain="government_public", question="What does 'public sector' refer to?",
         option_a="Privately owned businesses", option_b="Organizations and services owned or controlled by the government",
         option_c="Non-profit charities only", option_d="International corporations", correct_answer=1),
    dict(domain="government_public", question="What is 'social welfare policy' designed to address?",
         option_a="Corporate tax rates", option_b="The wellbeing and basic needs of citizens, especially vulnerable groups",
         option_c="International trade tariffs", option_d="Stock market regulation", correct_answer=1),
    dict(domain="government_public", question="What does 'devolution' mean in governance?",
         option_a="Transfer of power from central to regional/local government", option_b="Abolishing all levels of government",
         option_c="Merging multiple countries into one", option_d="A type of tax increase", correct_answer=0),
    dict(domain="government_public", question="What is the purpose of a 'public hearing'?",
         option_a="To privately negotiate contracts", option_b="To gather public input on proposed policies or projects",
         option_c="To conduct a criminal trial", option_d="To audit a company's finances", correct_answer=1),
    dict(domain="government_public", question="What does 'accountability' mean for public officials?",
         option_a="Being answerable for their actions and decisions", option_b="Having unlimited authority",
         option_c="Working without any oversight", option_d="Being exempt from public criticism", correct_answer=0),
    dict(domain="government_public", question="What is the role of the executive branch in government?",
         option_a="Interpreting laws", option_b="Enforcing and implementing laws and policies",
         option_c="Writing the constitution", option_d="Conducting court trials", correct_answer=1),

    # ───────────────────────── Agriculture ─────────────────────────
    dict(domain="agriculture", question="What is 'crop rotation'?",
         option_a="Growing the same crop repeatedly in the same field", option_b="Growing different crops in sequence on the same land to maintain soil health",
         option_c="Harvesting crops at night", option_d="A method of irrigation", correct_answer=1),
    dict(domain="agriculture", question="What does 'irrigation' refer to?",
         option_a="The artificial application of water to land for crop growth", option_b="The process of harvesting grain",
         option_c="A type of soil testing", option_d="A pest control method", correct_answer=0),
    dict(domain="agriculture", question="What is the primary purpose of using fertilizers?",
         option_a="To control weeds", option_b="To supply nutrients that improve soil fertility and crop yield",
         option_c="To irrigate fields", option_d="To harvest crops faster", correct_answer=1),
    dict(domain="agriculture", question="What does 'organic farming' emphasize?",
         option_a="Using synthetic pesticides extensively", option_b="Avoiding synthetic chemicals and relying on natural farming methods",
         option_c="Growing crops only indoors", option_d="Using genetically modified seeds exclusively", correct_answer=1),
    dict(domain="agriculture", question="What is 'soil erosion'?",
         option_a="The enrichment of soil with nutrients", option_b="The wearing away of topsoil by wind, water, or other forces",
         option_c="A method of plowing fields", option_d="The process of planting seeds", correct_answer=1),
    dict(domain="agriculture", question="What does 'livestock' refer to?",
         option_a="Farm equipment used for plowing", option_b="Domesticated animals raised for food, labor, or other products",
         option_c="Stored grain in a warehouse", option_d="A type of fertilizer", correct_answer=1),
    dict(domain="agriculture", question="What is the purpose of pesticides in agriculture?",
         option_a="To improve soil texture", option_b="To control or eliminate pests that damage crops",
         option_c="To increase water retention", option_d="To speed up photosynthesis", correct_answer=1),
    dict(domain="agriculture", question="What does 'horticulture' focus on?",
         option_a="Livestock breeding", option_b="The cultivation of fruits, vegetables, flowers, and plants",
         option_c="Fishing and aquaculture", option_d="Soil chemistry only", correct_answer=1),
    dict(domain="agriculture", question="What is 'crop yield'?",
         option_a="The type of soil used for farming", option_b="The amount of a crop produced per unit of land area",
         option_c="The price of crops in the market", option_d="The season in which crops are planted", correct_answer=1),
    dict(domain="agriculture", question="What does 'sustainable agriculture' aim to achieve?",
         option_a="Maximizing short-term profit regardless of environmental impact", option_b="Meeting current food needs without compromising future generations' resources",
         option_c="Eliminating all use of machinery", option_d="Farming only in greenhouses", correct_answer=1),
    dict(domain="agriculture", question="What is 'aquaculture'?",
         option_a="The farming of aquatic organisms like fish and shellfish", option_b="A method of dryland farming",
         option_c="The study of soil composition", option_d="A type of crop rotation", correct_answer=0),
    dict(domain="agriculture", question="What does 'GMO' stand for in agriculture?",
         option_a="Genetically Modified Organism", option_b="General Market Output",
         option_c="Government Managed Operation", option_d="Growth Monitoring Overview", correct_answer=0),
    dict(domain="agriculture", question="What is 'harvesting'?",
         option_a="Planting seeds in prepared soil", option_b="The process of gathering mature crops from the field",
         option_c="Applying fertilizer to soil", option_d="Removing weeds from a field", correct_answer=1),
    dict(domain="agriculture", question="What does 'agroforestry' combine?",
         option_a="Trees and crops/livestock on the same land", option_b="Only large-scale monoculture farming",
         option_c="Fishing and forestry only", option_d="Urban construction and farming", correct_answer=0),
    dict(domain="agriculture", question="What is the purpose of a 'greenhouse' in farming?",
         option_a="To store harvested grain", option_b="To create a controlled environment for growing plants year-round",
         option_c="To house livestock", option_d="To process dairy products", correct_answer=1),
    dict(domain="agriculture", question="What does 'soil pH' measure?",
         option_a="The moisture content of soil", option_b="The acidity or alkalinity of soil",
         option_c="The temperature of soil", option_d="The nutrient density of soil", correct_answer=1),
    dict(domain="agriculture", question="What is 'monoculture' farming?",
         option_a="Growing a single crop species over a large area repeatedly", option_b="Growing many different crops together",
         option_c="Raising multiple types of livestock", option_d="A method of organic composting", correct_answer=0),
    dict(domain="agriculture", question="What does 'drip irrigation' involve?",
         option_a="Flooding entire fields with water", option_b="Delivering water directly to plant roots through tubes and emitters",
         option_c="Spraying water into the air over crops", option_d="Relying only on rainfall", correct_answer=1),
    dict(domain="agriculture", question="What is 'composting'?",
         option_a="A method of pest control using chemicals", option_b="Recycling organic waste into nutrient-rich soil material",
         option_c="A technique for storing grain long-term", option_d="A type of irrigation system", correct_answer=1),
    dict(domain="agriculture", question="What does 'yield per acre' help farmers measure?",
         option_a="The cost of farm labor", option_b="Productivity of land for a given crop",
         option_c="The market price of a crop", option_d="The number of workers needed", correct_answer=1),
]

DOMAINS = sorted(set(q["domain"] for q in questions))

with app.app_context():
    for domain in DOMAINS:
        deleted = AssessmentQuestion.query.filter_by(domain=domain).delete()
        print(f"Cleared {deleted} existing question(s) for '{domain}'")

    db.session.add_all([AssessmentQuestion(**q) for q in questions])
    db.session.commit()

    for domain in DOMAINS:
        count = AssessmentQuestion.query.filter_by(domain=domain).count()
        print(f"{domain}: {count} questions")

print(f"\nDone. Seeded {len(questions)} questions across {len(DOMAINS)} domains.")
